name: brisbert
author: Luke Brooker

url: "http://localhost:4000"

paginate: 10

markdown: rdiscount
permalink: /blog/:title
pygments: true

source: ./src
destination: ./_site

include: [.htaccess]
exclude: [brisbert.sublime-project, brisbert.sublime-workspace, config.rb, sass]

# Plugins config

